image:
  repository: "161805283944.dkr.ecr.us-west-2.amazonaws.com/frontend"
  tag: "adc1ea32e9301dc91beb52ede6daefd7d01ef13a"
  pullPolicy: IfNotPresent
imagePullSecrets: []
replicaCount: 2
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext:
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 101
  fsGroup: 101
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  host: habittracker.local
  path: /
  pathType: Prefix
config:
  REACT_APP_API_URL: "http://backend-service:5000"
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
nodeSelector: {}
tolerations: []
affinity: {}
