image:
  repository: "161805283944.dkr.ecr.us-west-2.amazonaws.com/notification-service"
  tag: "ac361cd12e68249fd2d8a0a7dd544002650a9085"
  pullPolicy: IfNotPresent
imagePullSecrets: []
replicaCount: 2
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
service:
  type: ClusterIP
  port: 5001
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  host: habittracker.32.188.82.206.nip.io
  path: /notify
  pathType: Prefix
config: {}
secret: {}
serviceMonitor:
  enabled: true
  interval: 30s
  path: /metrics
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
nodeSelector: {}
tolerations: []
affinity: {}
