apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: habit-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: rajulmewade618/habit-notification-service:latest
          ports:
            - containerPort: 5001
          envFrom:
            - secretRef:
                name: notification-secret
          env:
            - name: PORT
              value: "5001"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 15
