apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "chart.fullname" . }}-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}

data:
  PORT: {{ .Values.config.PORT | quote }}
  MONGO_URL: {{ .Values.config.MONGO_URL | quote }}
  NOTIFY_URL: {{ .Values.config.NOTIFY_URL | quote }}