{{- if and .Values.auth.enabled .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}

spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}

  secretStoreRef:
    name: {{ .Values.externalSecrets.storeName }}
    kind: ClusterSecretStore

  target:
    name: {{ include "chart.fullname" . }}-secret
    creationPolicy: Owner

  data:
    - secretKey: MONGO_INITDB_ROOT_USERNAME
      remoteRef:
        key: {{ .Values.externalSecrets.mongodbSecretsKey }}
        property: MONGO_INITDB_ROOT_USERNAME
    - secretKey: MONGO_INITDB_ROOT_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.mongodbSecretsKey }}
        property: MONGO_INITDB_ROOT_PASSWORD
{{- end }}
