apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-store
  namespace: argocd
spec:
  project: habit-tracker

  source:
    repoURL: https://github.com/rajul-mm1/Habit-Tracker-App.git
    targetRevision: main
    path: infra/external-secrets-store/chart
    helm:
      releaseName: external-secrets-store

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
