apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore

metadata:
  name: {{ .Values.name }}

spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.auth.serviceAccountName }}
            namespace: {{ .Values.auth.serviceAccountNamespace }}
