apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "chart.fullname" . }}-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}

data:
  BACKEND_URL: {{ .Values.config.BACKEND_URL | quote }}
  NOTIFY_URL: {{ .Values.config.NOTIFY_URL | quote }}