apiVersion: v1
kind: Secret

metadata:
  name: {{ include "chart.fullname" . }}-secret
  labels:
    {{- include "chart.labels" . | nindent 4 }}

type: Opaque

data:
  INTERNAL_SECRET: {{ .Values.secret.INTERNAL_SECRET | b64enc | quote }}